// import glightbox
import 'glightbox/dist/css/glightbox.css';

import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Personal Portfolio Next.js",
  description: "Generated by create next app",
};


import React from 'react';
import Header from './components/Header';
import Downloads from './components/Downloads';
import Tabs from './components/Tabs';

const Home: React.FC = () => {
  return (
    <html>
      <body>
        <div>
          <Header />
          <Downloads />
          <Tabs />
        </div>
      </body>
    </html>
  );
};

export default Home;