// importing icons
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'boxicons/css/boxicons.css';

// import bootstrap itself
import 'bootstrap/dist/css/bootstrap.css';

// import glightbox
import 'glightbox/dist/css/glightbox.css';

import Header from './components/Header';



import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Personal Portfolio Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Header />
        {children}
        </body>
    </html>
  );
}
